data folder: 
  - ./data/prediction/IterGNN_UAttentionConv/ 

number of vehicles: 20 # max number of vehicle in prediction dataset
num of obstacles: 4 # max number of obstacle in prediction dataset

car size: 
  - 1.0
  - 2.5

position tolerance: 1.25
angle tolerance: 0.2
stop tolerance: 0.05

save metrics: True