
data folder: ./data/test_dataset # path to save test dataset

data length each case: 4000
collision mode: True # higher priority than parking mode
parking mode: False     

problem collection: 
  - [1,0]
  - [1,1]
  - [1,2]
  - [1,3]
  - [1,4]
  - [2,0]
  - [2,1]
  - [2,2]
  - [2,3]
  - [2,4]
  - [3,0]
  - [3,1]
  - [3,2]
  - [3,3]
  - [3,4]
  - [4,0]
  - [4,1]
  - [4,2]
  - [4,3]
  - [5,0]
  - [5,1]
  - [5,2]
  - [6,0]
  - [6,1]
  - [6,2]