# config for simulation
horizon: 15 # prediction horizon for MPC
simulation time: 150 # number of iteration for each simulation
simutaion runs: 3000 # number of simulation
save failed samples: True

position tolerance: 1.0
angle tolerance: 0.2
stop tolerance: 0.05

random offset: train # set it to train to enable state quotient based random offset 
                     # or False to disable the offset
collect data: True # keep it True for collecting training data
collect trajectory: True
data folder: ./data/trainval_dataset/data_generation_new
show optimization: True # enable running of MPC, keep it as True for data generation

# config for MPC model
control init: ./data/mpc_initialization/hard_data # keep it empty for no initialization for MPC
        
distance cost: 1
angle cost: 0.5
collision cost: 200
collision radius: 5     
obstacle cost: 200
obstacle radius: 3
velocity cost: 10
velocity limit: 3.5
smoothness cost: 0.1
travel dist cost: 0
       

# config for visualization        
figure size: 8
figure limit: 30
ticks step: 5
car size: 
  - 1.0
  - 2.5
show plot: False
save plot: False
plot folder: ./plots/trainval_dataset/data_generation_new

# config for data generation
collision mode: True # higher priority than parking mode
parking mode: False      

problem collection: # [num of vehicle, num of obstacle]
  # - [1, 0]
  # - [1, 1]
  # - [1, 2]
  # - [1, 3]
  # - [1, 4]
  # - [2, 0]
  # - [2, 1]
  # - [2, 2]
  # - [2, 3]
  # - [2, 4]
  # - [3, 0]
  - [3, 1]
