# config for training
horizon: 1 # keep it as 1 for GNN training

train max epochs: 500
train patience: 15
batch size: 4096
        
initial learning rate: 0.01
weight decay: 0.000001

learning rate patience: 10
learning rate factor: 0.2
min learining rate: 0.00000001

# config for dataset
number of vehicles: 4 # max number of vehicle in trainval dataset
num of obstacles: 4 # max number of obstacle in trainval dataset 
data folder: 
  - ./data/trainval_dataset/data_generation_1
  - ./data/trainval_dataset/data_generation_2
  - ./data/trainval_dataset/data_generation_3

augmentation: False

# config for model
model folder: ./models     
model name: improved_model_hard_data
   
pretrained model: # leave it empty or give the path to the pretrained model

hard data mining:
  data folder extend: 
  - ./data/trainval_dataset/data_generation_extend_hard_data
  percent data used: 1
